"""adding on_delete to the models.

Revision ID: 9a4ba9ac260a
Revises: e938cc8fc11e
Create Date: 2025-01-03 02:49:31.464925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9a4ba9ac260a'
down_revision: Union[str, None] = 'e938cc8fc11e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
