"""user_id, project_id unique together.

Revision ID: e938cc8fc11e
Revises: 21e4f9f89cbe
Create Date: 2025-01-03 02:37:59.253833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e938cc8fc11e'
down_revision: Union[str, None] = '21e4f9f89cbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('projectaccess_user_id_key', 'projectaccess', type_='unique')
    op.create_unique_constraint('unique_user_project', 'projectaccess', ['user_id', 'project_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_user_project', 'projectaccess', type_='unique')
    op.create_unique_constraint('projectaccess_user_id_key', 'projectaccess', ['user_id'])
    # ### end Alembic commands ###
